### PR TITLE
Solution upgraded to .Net 5

### PR DESCRIPTION
**Pull request by hectortosa**
API and Test projects have been updated to .Net 5. Code changes were necessary to adapt to the new version:
- Changed `IHostingEnvironment`for `IWebHostEnvironment`
- Set `MvcOptions.EnableEndpointRouting` to false
- Reference `Newtonsoft.Json` package

Updated NuGet packages in the test project to the latest stable version.

Updated README.md to reflect the new requirements.

### CODE REVIEW

**Comment by knuxbbs** [comment]
This should be upgraded to .NET 6, since it's a LTS version and have support until November 2024.

**Comment by knuxbbs** [comment]
@albertattard This pull request is very important, since .NET Core 2.0 has been deprecated for a long time. On Ubuntu, for example, it's not that simple to install.

**Comment by hectortosa** [comment]
> This should be upgraded to .NET 6, since it's a LTS version and have support until November 2024.

Completely agree, when this PR was created NET6 was not released yet. I can upgrade this branch/PR to use NET6 👍

**Comment by hectortosa** [comment]
Upgraded to .NET 6 and updated README accordingly.

**Pull request closed without merging**
